//! Dictionaries (gazetteers) used by name and place detectors.
//!
//! The default dictionaries are embedded into the binary from `data/` so the
//! service has no runtime data dependency; extra files can be merged in from
//! configuration.

use crate::config::{DictClass, DictConfig};
use crate::error::{CoreError, Result};
use crate::inflect;
use std::collections::{HashMap, HashSet};
use std::path::Path;

const FIRST_NAMES_MALE: &str = include_str!("../../../data/first_names_male.txt");
const FIRST_NAMES_FEMALE: &str = include_str!("../../../data/first_names_female.txt");
const FIRST_NAMES_DIMINUTIVE: &str = include_str!("../../../data/first_names_diminutive.txt");
const PATRONYMICS: &str = include_str!("../../../data/patronymics.txt");
const SURNAMES: &str = include_str!("../../../data/surnames.txt");
const CITIES_RU: &str = include_str!("../../../data/cities_ru.txt");
const CITIES_WORLD: &str = include_str!("../../../data/cities_world.txt");
const REGIONS_RU: &str = include_str!("../../../data/regions_ru.txt");
const COUNTRIES: &str = include_str!("../../../data/countries.txt");
const PUBLIC_PERSONS: &str = include_str!("../../../data/public_persons.txt");

/// First names that are also common words; they count as names only with
/// supporting evidence (capitalisation plus a neighbouring surname or context).
const AMBIGUOUS_FIRST_NAMES: &[&str] = &[
    "август",
    "вера",
    "любовь",
    "надежда",
    "роман",
    "лев",
    "света",
    "мила",
    "роза",
    "лилия",
    "слава",
    "майя",
    "ника",
    "лада",
    "соня",
    "тома",
    "поля",
    "уля",
    "ева",
    "дина",
    "рита",
    "влада",
    "кира",
    "инна",
    "зина",
    "тая",
    "гена",
    "боря",
    "вася",
    "женя",
    "даня",
    "марина",
    "виктория",
    "тема",
    "лева",
    "заря",
    "искра",
    "идея",
    "свобода",
    "воля",
    "победа",
    "радость",
    "весна",
    "ася",
    "лора",
    "лана",
    "нона",
    "макс",
    "ник",
    "кир",
    "марк",
    "мира",
    "ольга",
    "олег",
    "игорь",
    "юлия",
    "лика",
    "лиля",
    "агата",
    "адам",
    "атеист",
    "мая",
    "аля",
    "оля",
    "ира",
    "юля",
    "аня",
    "таня",
    "маша",
    "катя",
    "лена",
    "даша",
    "вика",
    "настя",
    "лиза",
    "ваня",
    "коля",
    "петя",
    "саша",
    "дима",
    "миша",
    "паша",
    "рома",
    "юра",
    "сеня",
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PlaceKind {
    City,
    Region,
    Country,
}

#[derive(Clone, Debug)]
pub struct PlaceEntry {
    /// Folded canonical name.
    pub name: String,
    pub kind: PlaceKind,
}

#[derive(Clone, Debug)]
pub struct PublicPerson {
    /// Folded nominative surname lemma.
    pub surname: String,
    pub first_name: Option<String>,
    pub patronymic: Option<String>,
}

#[derive(Clone, Debug, Default)]
pub struct Dictionaries {
    /// Every case form of every first name (folded).
    pub first_names: HashSet<String>,
    /// Nominative first names (folded).
    pub first_names_nom: HashSet<String>,
    /// Inflected form → nominative, for entity identity across case forms.
    pub first_name_nominative: HashMap<String, String>,
    pub male_names: HashSet<String>,
    pub female_names: HashSet<String>,
    /// Sorted nominative names and surnames for deterministic synthetic values.
    pub male_names_list: Vec<String>,
    pub female_names_list: Vec<String>,
    pub surnames_list: Vec<String>,
    pub cities_list: Vec<String>,
    pub ambiguous_first_names: HashSet<String>,
    /// Nominative first names transliterated to Latin (card holder names).
    pub first_names_latin: HashSet<String>,
    /// Every case form of every dictionary patronymic (folded).
    pub patronymics: HashSet<String>,
    /// Male nominative surnames (folded).
    pub surnames: HashSet<String>,
    /// Places in canonical form; inflected forms are generated by the gazetteer.
    pub places: Vec<PlaceEntry>,
    /// Country name forms (folded) for citizenship detection.
    pub country_forms: Vec<String>,
    pub public_persons: Vec<PublicPerson>,
}

pub fn fold(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.trim().chars() {
        match ch {
            'Ё' | 'ё' => out.push('е'),
            _ => out.extend(ch.to_lowercase()),
        }
    }
    out
}

/// GOST-style transliteration used on bank cards (approximate).
pub fn transliterate(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        let t: &str = match c {
            'а' => "a",
            'б' => "b",
            'в' => "v",
            'г' => "g",
            'д' => "d",
            'е' => "e",
            'ж' => "zh",
            'з' => "z",
            'и' => "i",
            'й' => "y",
            'к' => "k",
            'л' => "l",
            'м' => "m",
            'н' => "n",
            'о' => "o",
            'п' => "p",
            'р' => "r",
            'с' => "s",
            'т' => "t",
            'у' => "u",
            'ф' => "f",
            'х' => "kh",
            'ц' => "ts",
            'ч' => "ch",
            'ш' => "sh",
            'щ' => "shch",
            'ъ' | 'ь' => "",
            'ы' => "y",
            'э' => "e",
            'ю' => "yu",
            'я' => "ya",
            other => {
                out.push(other);
                continue;
            }
        };
        out.push_str(t);
    }
    out
}

fn lines(text: &str) -> impl Iterator<Item = &str> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
}

impl Dictionaries {
    /// Dictionaries embedded at build time.
    pub fn builtin() -> Self {
        let mut d = Self::default();
        d.add_first_names(lines(FIRST_NAMES_MALE), Some(true));
        d.add_first_names(lines(FIRST_NAMES_FEMALE), Some(false));
        d.add_first_names(lines(FIRST_NAMES_DIMINUTIVE), None);
        d.add_patronymics(lines(PATRONYMICS));
        d.add_surnames(lines(SURNAMES));
        d.add_places(lines(CITIES_RU), PlaceKind::City);
        d.add_places(lines(CITIES_WORLD), PlaceKind::City);
        d.add_places(lines(REGIONS_RU), PlaceKind::Region);
        d.add_countries(lines(COUNTRIES));
        d.add_public_persons(lines(PUBLIC_PERSONS));
        d.ambiguous_first_names = AMBIGUOUS_FIRST_NAMES
            .iter()
            .flat_map(|n| inflect::first_name_forms(n))
            .collect();
        d.finalize();
        d
    }

    /// Rebuilds the sorted lists used for synthetic values.
    pub fn finalize(&mut self) {
        let sorted = |set: &HashSet<String>| {
            let mut v: Vec<String> = set.iter().cloned().collect();
            v.sort();
            v
        };
        self.male_names_list = sorted(&self.male_names);
        self.female_names_list = sorted(&self.female_names);
        let mut surnames: Vec<String> = self
            .surnames
            .iter()
            .filter(|s| {
                s.chars().count() >= 5
                    && (s.ends_with("ов") || s.ends_with("ев") || s.ends_with("ин"))
            })
            .cloned()
            .collect();
        surnames.sort();
        self.surnames_list = surnames;
        let mut cities: Vec<String> = self
            .places
            .iter()
            .filter(|p| p.kind == PlaceKind::City && !p.name.contains(' '))
            .map(|p| p.name.clone())
            .collect();
        cities.sort();
        cities.dedup();
        self.cities_list = cities;
    }

    /// Built-in dictionaries plus everything referenced by `cfg`.
    pub fn from_config(cfg: &DictConfig, extra_public_persons: &[String]) -> Result<Self> {
        let mut d = Self::builtin();
        if let Some(dir) = &cfg.dir {
            d.load_dir(dir)?;
        }
        for extra in &cfg.extra {
            let text = std::fs::read_to_string(&extra.path).map_err(|e| {
                CoreError::Dictionary(format!("cannot read {}: {e}", extra.path.display()))
            })?;
            d.add_class(extra.class, lines(&text));
        }
        d.add_public_persons(extra_public_persons.iter().map(String::as_str));
        d.finalize();
        Ok(d)
    }

    fn load_dir(&mut self, dir: &Path) -> Result<()> {
        let files: &[(&str, DictClass)] = &[
            ("first_names_male.txt", DictClass::FirstName),
            ("first_names_female.txt", DictClass::FirstName),
            ("first_names_diminutive.txt", DictClass::FirstName),
            ("patronymics.txt", DictClass::Patronymic),
            ("surnames.txt", DictClass::Surname),
            ("cities_ru.txt", DictClass::City),
            ("cities_world.txt", DictClass::City),
            ("regions_ru.txt", DictClass::Region),
            ("countries.txt", DictClass::Country),
            ("public_persons.txt", DictClass::PublicPerson),
        ];
        for (name, class) in files {
            let path = dir.join(name);
            if path.exists() {
                let text = std::fs::read_to_string(&path).map_err(|e| {
                    CoreError::Dictionary(format!("cannot read {}: {e}", path.display()))
                })?;
                self.add_class(*class, lines(&text));
            }
        }
        Ok(())
    }

    fn add_class<'a>(&mut self, class: DictClass, items: impl Iterator<Item = &'a str>) {
        match class {
            DictClass::FirstName => self.add_first_names(items, None),
            DictClass::Patronymic => self.add_patronymics(items),
            DictClass::Surname => self.add_surnames(items),
            DictClass::City => self.add_places(items, PlaceKind::City),
            DictClass::Region => self.add_places(items, PlaceKind::Region),
            DictClass::Country => self.add_countries(items),
            DictClass::PublicPerson => self.add_public_persons(items),
        }
    }

    fn add_first_names<'a>(&mut self, items: impl Iterator<Item = &'a str>, male: Option<bool>) {
        for item in items {
            let nom = fold(item);
            if nom.is_empty() {
                continue;
            }
            match male {
                Some(true) => {
                    self.male_names.insert(nom.clone());
                }
                Some(false) => {
                    self.female_names.insert(nom.clone());
                }
                None => {}
            }
            for form in inflect::first_name_forms(&nom) {
                self.first_name_nominative
                    .entry(form.clone())
                    .or_insert_with(|| nom.clone());
                self.first_names.insert(form);
            }
            self.first_names_latin.insert(transliterate(&nom));
            self.first_names_nom.insert(nom);
        }
    }

    fn add_patronymics<'a>(&mut self, items: impl Iterator<Item = &'a str>) {
        for item in items {
            for form in inflect::patronymic_forms(&fold(item)) {
                self.patronymics.insert(form);
            }
        }
    }

    fn add_surnames<'a>(&mut self, items: impl Iterator<Item = &'a str>) {
        for item in items {
            let s = fold(item);
            if !s.is_empty() {
                self.surnames.insert(s);
            }
        }
    }

    fn add_places<'a>(&mut self, items: impl Iterator<Item = &'a str>, kind: PlaceKind) {
        for item in items {
            let name = fold(item);
            if !name.is_empty() {
                self.places.push(PlaceEntry { name, kind });
            }
        }
    }

    fn add_countries<'a>(&mut self, items: impl Iterator<Item = &'a str>) {
        for item in items {
            for form in item.split('|').map(fold).filter(|f| !f.is_empty()) {
                if !self.country_forms.contains(&form) {
                    self.places.push(PlaceEntry {
                        name: form.clone(),
                        kind: PlaceKind::Country,
                    });
                    self.country_forms.push(form);
                }
            }
        }
    }

    fn add_public_persons<'a>(&mut self, items: impl Iterator<Item = &'a str>) {
        for item in items {
            let parts: Vec<String> = item.split('|').map(fold).collect();
            let Some(surname) = parts.first().filter(|s| !s.is_empty()).cloned() else {
                continue;
            };
            let opt = |i: usize| parts.get(i).filter(|s| !s.is_empty()).cloned();
            self.public_persons.push(PublicPerson {
                surname,
                first_name: opt(1),
                patronymic: opt(2),
            });
        }
    }

    pub fn is_first_name(&self, folded: &str) -> bool {
        self.first_names.contains(folded)
    }

    pub fn is_ambiguous_first_name(&self, folded: &str) -> bool {
        self.ambiguous_first_names.contains(folded)
    }

    pub fn is_patronymic(&self, folded: &str) -> bool {
        self.patronymics.contains(folded) || inflect::is_patronymic_like(folded)
    }

    /// Nominative lemma if the token is a dictionary surname in any form.
    pub fn surname_lemma(&self, folded: &str) -> Option<String> {
        inflect::surname_lemmas(folded)
            .into_iter()
            .find(|l| self.surnames.contains(l))
    }

    /// Public person whose surname matches the lemma; the caller checks the
    /// first name when one is present in the text.
    pub fn public_person(&self, surname_lemma: &str) -> Option<&PublicPerson> {
        self.public_persons
            .iter()
            .find(|p| p.surname == surname_lemma)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_dictionaries_load() {
        let d = Dictionaries::builtin();
        assert!(d.first_names.len() > 1000);
        assert!(d.surnames.len() > 50_000);
        assert!(d.places.len() > 1000);
        assert!(d.is_first_name("ивана"));
        assert!(d.is_first_name("петра")); // Пётр folded
        assert!(d.is_patronymic("ивановича"));
        assert_eq!(d.surname_lemma("ивановой").as_deref(), Some("иванов"));
        assert!(d.public_person("пушкин").is_some());
        assert!(d.country_forms.iter().any(|c| c == "рф"));
        assert!(d.first_names_latin.contains("ivan"));
        assert!(d.is_ambiguous_first_name("веры"));
    }
}
